[project]
name = "tabfpn-experiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Brian Staber", email = "brian.staber@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.3.0",
    "matplotlib>=3.10.7",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "tabpfn>=2.2.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
